# Generated by Django 4.2.5 on 2023-09-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Passenger',
        ),
    ]
